# Generated by Django 3.0.7 on 2020-07-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=8, unique=True)),
                ('file', models.FileField(upload_to='upload/am/')),
            ],
        ),
        migrations.CreateModel(
            name='rep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=8, unique=True)),
                ('score', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
